---
title: "XGBoostTitanicAmmara"
author: "Yang Ge"
date: "6/19/2017"
output: html_document
---

* This example is based on [this](https://www.kaggle.com/ammara/titanic-competition-using-xgboost/code/code)

```{r, echo=TRUE}
require(xgboost)
require(tidyverse)
require(rpart)
set.seed(20121228)
train <- read.csv("train.csv")
test <- read.csv("test.csv")
```

* Doing some feature engineering

```{r}
test$Survived <- NA
combi <- rbind(train, test)
combi$Name <- as.character(combi$Name)
combi$Title <- sapply(combi$Name, FUN=function(x) {strsplit(x, split='[,.]')[[1]][2]})
combi$Title <- sub(' ', '', combi$Title)

table(combi$Title)
combi$Title[combi$Title %in% c('Mme', 'Mlle')] <- 'Mlle'
combi$Title[combi$Title %in% c('Capt', 'Don', 'Major', 'Sir')] <- 'Sir'
combi$Title[combi$Title %in% c('Dona', 'Lady', 'the Countess', 'Jonkheer')] <- 'Lady'
combi$Title <- factor(combi$Title)

combi$FamilySize <- combi$SibSp + combi$Parch + 1
combi$Surname <- sapply(combi$Name, FUN=function(x) {strsplit(x, split='[,.]')[[1]][1]})
combi$FamilyID <- paste(as.character(combi$FamilySize), combi$Surname, sep="")
combi$FamilyID[combi$FamilySize <= 2] <- 'Small'
combi$FamilyID[combi$FamilySize > 2] <- 'Big'

#table(combi$FamilyID)
combi$FamilyID <- factor(combi$FamilyID)

Agefit <- rpart(Age ~ Pclass + Sex + SibSp + Parch + Fare + Embarked + Title + FamilySize, data=combi[!is.na(combi$Age),], method="anova")
combi$Age[is.na(combi$Age)] <- predict(Agefit, combi[is.na(combi$Age),])

combi$Embarked[c(62,830)] = "S"
combi$Embarked <- factor(combi$Embarked)
#which(is.na(combi$Fare))
combi$Fare[1044] <- median(combi$Fare, na.rm=TRUE)

combi$FamilyID2 <- combi$FamilyID
combi$FamilyID2 <- as.character(combi$FamilyID2)
combi$FamilyID2[combi$FamilySize <= 3] <- 'Small'
combi$FamilyID2 <- factor(combi$FamilyID2)

combi2 <- combi[, -c(1,4,9, 11, 15,17)]

```

* next, convert the factors to numerical, required by xgboost

```{r}
combi2$Pclass <- as.numeric(combi2$Pclass) - 1
combi2$Sex <- as.numeric(combi2$Sex) -1
combi2$Embarked <- as.numeric(combi2$Embarked) -1
combi2$Title <- as.numeric(combi2$Title) -1
combi2$FamilySize <- as.numeric(combi2$FamilySize) -1
combi2$FamilyID <- as.numeric(combi2$FamilyID) -1
```

* convert it to Matrix

```{r}
combi2 <- as.matrix(combi2)
train <- combi2[1:891,]
test <- combi2[892:1309,]
param <- list("objective" = "binary:logistic")

cv.nround <- 15
cv.nfold <- 3

xgboost_cv = xgb.cv(param=param, data = train[, -c(1)], label = train[, c(1)], nfold = cv.nfold, nrounds = cv.nround)

nround  = 15
fit_xgboost <- xgboost(param =param, data = train[, -c(1)], label = train[, c(1)], nrounds=nround)

names <- dimnames(train)[[2]]

importance_matrix <- xgb.importance(names, model = fit_xgboost)
xgb.plot.importance(importance_matrix)

```
